--liquibase formatted sql


-- changeset albert:20200504-185300-1

-- MySQL Script generated by MySQL Workbench
-- Wed Jul  1 01:06:16 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';






-- -----------------------------------------------------
-- Table province
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `province` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,

  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) )
 
 ENGINE = InnoDB
;


-- -----------------------------------------------------
-- Table town
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `town` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `province_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  
 
    CONSTRAINT `town_province_fk`
    FOREIGN KEY (`province_id`)
    REFERENCES `province` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  
 
ENGINE = InnoDB
;


