--liquibase formatted sql


-- changeset albert:20200504-185300-1
-- Creació de la bd. De la generacion del workbench para que vaya en prod i prepro hay que:
-- Comentar el create schema y el use
-- Eliminar el `reports_service`.
-- Eliminar el   VISIBLE    de los indices
-- Eliminar el DEFAULT CHARACTER SET = DEFAULT
-- Taula report_template, camp is_, afegir el visible, que el replace d'abans el treu
-- Taula block afegir el visible a is__subject que el replace el treu

-- MySQL Script generated by MySQL Workbench
-- Wed Jul  1 01:06:16 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema reports_service
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema reports_service
-- -----------------------------------------------------
-- CREATE SCHEMA IF NOT EXISTS `reports_service` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish2_ci ;
-- USE `reports_service` ;

-- -----------------------------------------------------
-- Table `report_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `report_category` ;

CREATE TABLE IF NOT EXISTS `report_category` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `federation` VARCHAR(10) NOT NULL,
  `last_update` TIMESTAMP NULL,
  `deleted` TIMESTAMP NULL,
  `last_action_user` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `unique_name` (`name` ASC, `federation` ASC) ,
  INDEX `index_fed` (`federation` ASC) ,
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) )
ENGINE = InnoDB
;


-- -----------------------------------------------------
-- Table `informer_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `informer_type` ;

CREATE TABLE IF NOT EXISTS `informer_type` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  INDEX `code_idx` (`code` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `subject_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `subject_type` ;

CREATE TABLE IF NOT EXISTS `subject_type` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  INDEX `code_idx` (`code` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `report_template`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `report_template` ;

CREATE TABLE IF NOT EXISTS `report_template` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `federation` VARCHAR(10) NOT NULL,
  `status` TINYINT NOT NULL,
  `created` DATETIME NULL,
  `is_visible` TINYINT NOT NULL DEFAULT 0,
  `show_referee` TINYINT NOT NULL DEFAULT 0,
  `portal` INT NOT NULL DEFAULT 0,
  `allow_not_designated` TINYINT NOT NULL DEFAULT 0,
  `is_match_report` TINYINT NOT NULL DEFAULT 0,
  `informer_type_id` INT(10) UNSIGNED NOT NULL,
  `subject_type_id` INT(10) UNSIGNED NOT NULL,
  `report_category_id` INT(10) UNSIGNED NOT NULL,
  `last_update` TIMESTAMP NULL,
  `deleted` TIMESTAMP NULL,
  `last_action_user` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  INDEX `report_template_federation_idx` (`federation` ASC) ,
  INDEX `informer_type_report_template_fk_idx` (`informer_type_id` ASC) ,
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) ,
  INDEX `subject_type_report_template_idx` (`subject_type_id` ASC) ,
  INDEX `report_category_report_template_fk_idx` (`report_category_id` ASC) ,
  CONSTRAINT `informer_type_report_template_fk`
    FOREIGN KEY (`informer_type_id`)
    REFERENCES `informer_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `subject_type_report_template`
    FOREIGN KEY (`subject_type_id`)
    REFERENCES `subject_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `report_category_report_template_fk`
    FOREIGN KEY (`report_category_id`)
    REFERENCES `report_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
;


-- -----------------------------------------------------
-- Table `poll`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `poll` ;

CREATE TABLE IF NOT EXISTS `poll` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `name` VARCHAR(200) NOT NULL,
  `federation` VARCHAR(10) NOT NULL,
  `status` TINYINT NOT NULL,
  `activation_time` DATETIME NULL,
  `ending_time` DATETIME NULL,
  `anonymous` TINYINT NOT NULL DEFAULT 0,
  `description` TEXT NULL,
  `login_required` TINYINT NOT NULL DEFAULT 1,
  `change_answer_allowed` TINYINT NOT NULL DEFAULT 0,
  `informer_type_id` INT(10) UNSIGNED NOT NULL,
  `informer_categories` VARCHAR(100) NOT NULL,
  `last_update` TIMESTAMP NULL,
  `deleted` TIMESTAMP NULL,
  `last_action_user` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) ,
  INDEX `informer_type_fk_idx` (`informer_type_id` ASC) ,
  INDEX `federation_index` (`federation` ASC) ,
  CONSTRAINT `poll_informer_type_fk`
    FOREIGN KEY (`informer_type_id`)
    REFERENCES `informer_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `block`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `block` ;

CREATE TABLE IF NOT EXISTS `block` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NULL,
  `is_visible_subject` TINYINT NOT NULL DEFAULT 1,
  `order_num` INT NOT NULL,
  `report_template_id` INT(10) UNSIGNED NULL,
  `poll_id` INT(10) UNSIGNED NULL,
  `last_update` TIMESTAMP NULL,
  `deleted` TIMESTAMP NULL,
  `last_action_user` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  INDEX `tipus_informe_kf_idx` (`report_template_id` ASC) ,
  INDEX `poll_fk_idx` (`poll_id` ASC) ,
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) ,
  CONSTRAINT `block_report_template_fk`
    FOREIGN KEY (`report_template_id`)
    REFERENCES `report_template` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `block_poll_fk`
    FOREIGN KEY (`poll_id`)
    REFERENCES `poll` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
;


-- -----------------------------------------------------
-- Table `answer_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `answer_type` ;

CREATE TABLE IF NOT EXISTS `answer_type` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(15) NOT NULL,
  `is_multiple_choice` TINYINT NOT NULL DEFAULT 0,
  `is_value_range` TINYINT NOT NULL DEFAULT 0,
  `is_allowed_in_poll` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `block_template`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `block_template` ;

CREATE TABLE IF NOT EXISTS `block_template` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `federation` VARCHAR(10) NOT NULL,
  `type` INT(10) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NULL,
  `order_num` INT NOT NULL,
  `is_visible_subject` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  INDEX `block_template_fede_type_idx` (`federation` ASC, `type` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `question`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `question` ;

CREATE TABLE IF NOT EXISTS `question` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `value` TEXT NOT NULL,
  `has_answer` TINYINT NULL DEFAULT 1,
  `mandatory` TINYINT NOT NULL DEFAULT 1,
  `order_num` INT NOT NULL,
  `answer_type_id` INT(10) UNSIGNED NOT NULL,
  `block_id` INT(10) UNSIGNED NULL,
  `block_template_id` INT(10) UNSIGNED NULL,
  `automatic_answer_name` VARCHAR(45) NULL COMMENT 'Para preguntas de plantillas de bloque nombre del campo del dto de entrada a la peticion con los datos que se van a informar en esta pregunta.',
  `last_update` TIMESTAMP NULL,
  `deleted` TIMESTAMP NULL,
  `last_action_user` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  INDEX `answer_type_fk_idx` (`answer_type_id` ASC) ,
  INDEX `question_block_fk_idx` (`block_id` ASC) ,
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) ,
  INDEX `question_predefined_block_fk_idx` (`block_template_id` ASC) ,
  CONSTRAINT `question_answer_type_fk`
    FOREIGN KEY (`answer_type_id`)
    REFERENCES `answer_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `question_block_fk`
    FOREIGN KEY (`block_id`)
    REFERENCES `block` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `question_block__template_fk`
    FOREIGN KEY (`block_template_id`)
    REFERENCES `block_template` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `answer_option`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `answer_option` ;

CREATE TABLE IF NOT EXISTS `answer_option` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `value` TEXT NOT NULL,
  `color` VARCHAR(50) NULL,
  `description` VARCHAR(250) NULL,
  `question_id` INT(10) UNSIGNED NOT NULL,
  `order_num` INT NOT NULL,
  `last_update` TIMESTAMP NULL,
  `deleted` TIMESTAMP NULL,
  `last_action_user` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  INDEX `question_answer_option_fk_idx` (`question_id` ASC) ,
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) ,
  CONSTRAINT `question_answer_option_fk`
    FOREIGN KEY (`question_id`)
    REFERENCES `question` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `campaign`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `campaign` ;

CREATE TABLE IF NOT EXISTS `campaign` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  `report_template_id` INT(10) UNSIGNED NOT NULL,
  `last_update` TIMESTAMP NULL,
  `deleted` TIMESTAMP NULL,
  `last_action_user` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  INDEX `campaign_report_template_fk_idx` (`report_template_id` ASC) ,
  CONSTRAINT `campaign_report_template_fk`
    FOREIGN KEY (`report_template_id`)
    REFERENCES `report_template` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
;


-- -----------------------------------------------------
-- Table `form`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `form` ;

CREATE TABLE IF NOT EXISTS `form` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `subject_uuid` VARCHAR(36) NULL,
  `informer_uuid` VARCHAR(36) NOT NULL,
  `status` TINYINT UNSIGNED NOT NULL,
  `assigned` DATETIME NULL COMMENT 'Fecha en que se ha asignado el formulario al informer',
  `scheduled_fill_out_date` DATETIME NULL COMMENT 'Fecha prevista de completar el informe',
  `fill_out_date` DATETIME NULL,
  `visualized` TINYINT NOT NULL DEFAULT 0,
  `report_template_id` INT(10) UNSIGNED NULL,
  `poll_id` INT(10) UNSIGNED NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) ,
  INDEX `subject_uuid` (`subject_uuid` ASC) ,
  INDEX `informer_uuid` (`informer_uuid` ASC) ,
  INDEX `report_template_fk_idx` (`report_template_id` ASC) ,
  INDEX `poll_fk_idx` (`poll_id` ASC) ,
  CONSTRAINT `form_report_template_fk`
    FOREIGN KEY (`report_template_id`)
    REFERENCES `report_template` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `form_poll_fk`
    FOREIGN KEY (`poll_id`)
    REFERENCES `poll` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
;


-- -----------------------------------------------------
-- Table `answer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `answer` ;

CREATE TABLE IF NOT EXISTS `answer` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `form_id` INT(10) UNSIGNED NOT NULL,
  `question_id` INT(10) UNSIGNED NOT NULL,
  `value` TEXT NULL,
  `answer_time` DATETIME NULL COMMENT '??',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  INDEX `report_fk_idx` (`form_id` ASC) ,
  INDEX `question_fk_idx` (`question_id` ASC) ,
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) ,
  CONSTRAINT `answer_form_fk`
    FOREIGN KEY (`form_id`)
    REFERENCES `form` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `answer_question_fk`
    FOREIGN KEY (`question_id`)
    REFERENCES `question` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `answer_template`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `answer_template` ;

CREATE TABLE IF NOT EXISTS `answer_template` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `federation` VARCHAR(10) NOT NULL,
  `language` VARCHAR(2) NOT NULL,
  `answer_type_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  INDEX `answer_type_id_idx` (`answer_type_id` ASC) ,
  INDEX `federation_idx` (`federation` ASC) ,
  INDEX `federation_lang_idx` (`federation` ASC, `language` ASC) ,
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) ,
  CONSTRAINT `option_template_answer_type_id`
    FOREIGN KEY (`answer_type_id`)
    REFERENCES `answer_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `selected_answer_option`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `selected_answer_option` ;

CREATE TABLE IF NOT EXISTS `selected_answer_option` (
  `answer_id` INT(10) UNSIGNED NOT NULL,
  `answer_option_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`answer_id`, `answer_option_id`),
  INDEX `fk_answer_has_answer_option_answer_option1_idx` (`answer_option_id` ASC) ,
  INDEX `fk_answer_has_answer_option_answer1_idx` (`answer_id` ASC) ,
  CONSTRAINT `fk_answer_has_answer_option_answer1`
    FOREIGN KEY (`answer_id`)
    REFERENCES `answer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_answer_has_answer_option_answer_option1`
    FOREIGN KEY (`answer_option_id`)
    REFERENCES `answer_option` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `answer_option_template`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `answer_option_template` ;

CREATE TABLE IF NOT EXISTS `answer_option_template` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `value` TEXT NOT NULL,
  `color` VARCHAR(50) NULL,
  `description` VARCHAR(250) NULL,
  `order_num` INT UNSIGNED NOT NULL,
  `answer_template_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  INDEX `answer_option_template_answer_template_fk_idx` (`answer_template_id` ASC) ,
  CONSTRAINT `answer_option_template_answer_template_fk`
    FOREIGN KEY (`answer_template_id`)
    REFERENCES `answer_template` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `permission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `permission` ;

CREATE TABLE IF NOT EXISTS `permission` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `federation` VARCHAR(10) NULL,
  `name` VARCHAR(100) NOT NULL,
  `can_edit` TINYINT NOT NULL DEFAULT 0,
  `report_category_id` INT(10) UNSIGNED NULL,
  `deleted` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  INDEX `permission_reports_category_idx` (`report_category_id` ASC) ,
  INDEX `name_federation_idx` (`name` ASC, `federation` ASC) ,
  CONSTRAINT `permission_reports_category`
    FOREIGN KEY (`report_category_id`)
    REFERENCES `report_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
